---
- name: (GITLAB-CE) Install prerequisites
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - perl
    - policycoreutils-python
    - openssh-server

- name: (GITLAB-CE) Check if GitLab-CE is already installed
  stat:
    path: /etc/gitlab
  register: gitlab

- name: (GITLAB-CE) Enaable sshd
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    masked: no

- name: (GITLAB-CE) Start sshd
  ansible.builtin.systemd:
    state: started
    name: sshd  

- name: (GITLAB-CE) Download GitLab-CE script
  shell: >
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash

- name: (GITLAB-CE) Execute GitLab-CE CentOS script
  shell: >
    EXTERNAL_URL="{{ gitlab_hostname }}" yum install -y gitlab-ce
