    - name: Install snapd
      yum: name=snapd state=latest
      notify: snapd.socket

    - name: Create symbolic link
      file: 
           src: /var/lib/snapd/snap
           dest: /snap
           state: link

    - name: Install certbot
      ansible.builtin.shell:
           cmd: sudo snap install --classic certbot

    - name: Create symbolic link
      file: 
           src: /snap/bin/certbot
           dest: /usr/bin/certbot
           state: link
    
    - name: Install certbot
      ansible.builtin.shell:
           cmd: sudo certbot --nginx -n -d www.grachikn.ru -m ngrachik@mail.ru --redirect

    - name: Reload nginx
      ansible.builtin.shell:
           cmd: service nginx reload
    


    - name: create letsencrypt directory
      file: name=/var/www/letsencrypt state=directory
      