    - name: Install EPEL Repo
      yum:
        name=epel-release
        state=present

    - name: Install snapd
      yum: name=snapd state=latest
    
    - name: Enable systemd
      shell: systemctl enable --now snapd.socket
    
    - name: Create symbolic link
      shell: sudo ln -s /var/lib/snapd/snap /snap

    - name: Install certbot snap with option --classic
      shell: sudo snap install --classic certbot

    - name: Do not count this as a failure
      ansible.builtin.command: /bin/false
          ignore_errors: yes
   
    - name: Pause for 1 minutes 
      ansible.builtin.pause:
          seconds: 20

    - name: Install certbot snap with option --classic
      shell: sudo snap install --classic certbot

    # - name: Install certbot snap with option --classic
    #   community.general.snap:
    #         name: certbot
    #         classic: yes
    
    # - name: Install cert
    #   shell: sudo certbot --nginx --dry-run -n -d www.grachikn.ru -m ngrachik@mail.ru --redirect --agree-tos

    - name: Nginx reload
      shell: nginx -s reload
      