    - name: (LETSENCRYPT) Install snapd
      yum: name=snapd state=latest
    
    - name: (LETSENCRYPT) Enable systemd
      shell: >
        systemctl enable --now snapd.socket
    
    - name: (LETSENCRYPT) Create symbolic link
      shell: >
        ln -s /var/lib/snapd/snap /snap    

    - name: (LETSENCRYPT) sudo snap install core with error
      shell: > 
          sudo snap install core; sudo snap refresh core
      ignore_errors: True

    - name: (LETSENCRYPT) sudo snap install core one more time
      shell: > 
          sudo snap install core; sudo snap refresh core

    - name: (LETSENCRYPT) ln -s /snap/bin/certbot /usr/bin/certbot
      shell: > 
          ln -s /snap/bin/certbot /usr/bin/certbot

    - name: (LETSENCRYPT) Install certbot snap with option --classic
      shell: >
           snap install --classic certbot
   
    - name: (LETSENCRYPT) Install cert for my domains
      shell: > 
          certbot --nginx -n -d www.grachikn.ru -d grafana.grachikn.ru -d prometheus.grachikn.ru -d gitlab.grachikn.ru -d alertmanager.grachikn.ru -m ngrachik@mail.ru --redirect --agree-tos
# 
    - name: Nginx reload
      shell: service nginx reload
      