    - name: Install EPEL Repo
      yum:
        name=epel-release
        state=present

    - name: Install snapd
      yum: name=snapd state=latest
    
    - name: Enable systemd
      shell: systemctl enable --now snapd.socket
    
    - name: Create symbolic link
      shell: sudo ln -s /var/lib/snapd/snap /snap     

    - name: Install certbot snap with option --classic
      shell: sudo snap install --classic certbot
      ignore_errors: True
   
    - name: Pause for 20 seconds
      ansible.builtin.pause:
          seconds: 5

    - name: Install certbot snap with option --classic
      shell: sudo snap install --classic certbot
   
    - name: Install cert
      shell: sudo certbot --nginx --dry-run -n -d www.grachikn.ru -d www.grafana.grachikn.ru -d www.prometheus.grachikn.ru -d www.alertmanager.grachikn.ru -m ngrachik@mail.ru --redirect --agree-tos

    - name: Nginx reload
      shell: service nginx reload
      