    - name: Install snapd
      yum: name=snapd state=latest
    
    - name: Enable systemd
      shell: >
        systemctl enable --now snapd.socket
    
    - name: Create symbolic link
      shell: >
        ln -s /var/lib/snapd/snap /snap    

    - name: sudo snap install core; sudo snap refresh core 
      shell: > 
          snap install core

    - name: snap refresh core 
      shell: > 
          snap refresh core 

    - name: ln -s /snap/bin/certbot /usr/bin/certbot
      shell: > 
          ln -s /snap/bin/certbot /usr/bin/certbot

    - name: Install certbot snap with option --classic
      shell: >
           snap install --classic certbot
      ignore_errors: True
   
    - name: Pause for 20 seconds
      ansible.builtin.pause:
          seconds: 5

    - name: Install certbot snap with option --classic
      shell: >
          snap install --classic certbot
   
    - name: Install cert
      shell: > 
          certbot --nginx --dry-run -n -d www.grachikn.ru -d grafana.grachikn.ru -d prometheus.grachikn.ru -d alertmanager.grachikn.ru -m ngrachik@mail.ru --redirect --agree-tos

    - name: Nginx reload
      shell: service nginx reload
      