---
# tasks file for runner
- name: (RUNNER) Get REPO for gitlab-runner
  shell: >
    curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | sudo bash

- name: (RUNNER) Install gitlab-runner
  yum:
    name: gitlab-runner
    state: latest

- name: (RUNNER) Enable runner
  ansible.builtin.systemd:
    name: gitlab-runner
    enabled: yes
    masked: no

- name: (RUNNER) Start runner
  ansible.builtin.systemd:
    state: started
    name: gitlab-runner