resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
  
    

    [app]
    app.${var.my_domain} ansible_host=${yandex_compute_instance.app.network_interface.0.nat_ip_address}

    [gitlab]
    gitlab.${var.my_domain} ansible_host=${yandex_compute_instance.gitlab.network_interface.0.nat_ip_address}
    
    [monitoring]
    monitoring.${var.my_domain} ansible_host=${yandex_compute_instance.monitoring.network_interface.0.nat_ip_address}

    [db_master]
    db01.${var.my_domain} ansible_host=${yandex_compute_instance.db-master.network_interface.0.nat_ip_address}

    [db_slave]
    db02.${var.my_domain} ansible_host=${yandex_compute_instance.db-slave.network_interface.0.nat_ip_address}

    [proxy]
    ${var.my_domain} ansible_host=${yandex_compute_instance.my-domain.network_interface.0.nat_ip_address}

    DOC
  filename = "../ansible/inventory.ini"
}

