---
- name: (WORPRESS) Install PHP rpm
  yum:
    name:
     - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     - yum-utils
    state: present

- name: (WORPRESS) --enable remi-php72
  shell: >
    yum-config-manager --enable remi-php72

- name: (WORPRESS) Install PHP
  yum:
    name:
     - php-cli 
     - php-fpm 
     - php-mysql 
     - php-json 
     - php-opcache 
     - php-mbstring 
     - php-xml 
     - php-gd 
     - php-curl
     
    #  - php72
    state: present

- name: (WORPRESS) Apply PHP config
  template:
    src: templates/www.conf.j2
    dest: /etc/php-fpm.d/www.conf

- name: (WORPRESS) Change ownership var/lib/php
  ansible.builtin.file:
    path: var/lib/php
    state: directory
    recurse: yes
    owner: nginx

- name: (WORPRESS) Enable php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    enabled: yes

- name: (WORPRESS) Run php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    state: started

- name: (WORPRESS) Create Directory for wordpress
  file:
    path: /var/www/wp
    state: directory

- name: (WORPRESS) Download file wordpress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /var/www/wp

- name: (WORPRESS) Extract WP into /var/www/wp
  ansible.builtin.unarchive:
    src: /var/www/wp/{{ version }}
    dest: /var/www/wp
    remote_src: yes


- name: (WORPRESS) Change ownership /var/www
  ansible.builtin.file:
    path: /var/www/wp
    state: directory
    recurse: yes
    owner: nginx

- name: (WORPRESS) Rename config
  shell: >
    mv /var/www/wp/wordpress/wp-config-sample.php /var/www/wp/wordpress/wp-config.php

- name: (WORPRESS) Apply WP config
  template:
    src: templates/wp-config.php.j2
    dest: /var/www/wp/wordpress/wp-config.php


- name: (WORPRESS) Restart nginx
  service: name=nginx state=restarted
