---
- name: (WORDPRESS) Install PHP rpm
  yum:
    name:
     - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     - yum-utils
    state: present

- name: (WORDPRESS) --enable remi-php72
  shell: >
    yum-config-manager --enable remi-php72

- name: (WORDPRESS) Install PHP
  yum:
    name:
     - php-cli 
     - php-fpm 
     - php-mysql 
     - php-json 
     - php-opcache 
     - php-mbstring 
     - php-xml 
     - php-gd 
     - php-curl
     
    #  - php72
    state: present

- name: (WORDPRESS) Apply PHP config
  template:
    src: templates/www.conf.j2
    dest: /etc/php-fpm.d/www.conf

- name: (WORDPRESS) Change ownership var/lib/php
  ansible.builtin.file:
    path: var/lib/php
    state: directory
    recurse: yes
    owner: nginx

- name: (WORDPRESS) Enable php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    enabled: yes

- name: (WORDPRESS) Run php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    state: started

- name: (WORDPRESS) Create Directory for wordpress
  file:
    path: /var/www/wp
    state: directory

- name: (WORDPRESS) Download file wordpress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /var/www/wp

- name: (WORDPRESS) Extract WP into /var/www/wp
  ansible.builtin.unarchive:
    src: /var/www/wp/{{ version }}
    dest: /var/www/wp
    remote_src: yes


- name: (WORDPRESS) Change ownership /var/www
  ansible.builtin.file:
    path: /var/www/wp
    state: directory
    recurse: yes
    owner: nginx

- name: (WORDPRESS) Rename config
  shell: >
    mv /var/www/wp/wordpress/wp-config-sample.php /var/www/wp/wordpress/wp-config.php

- name: (WORDPRESS) Apply WP config
  template:
    src: templates/wp-config.php.j2
    dest: /var/www/wp/wordpress/wp-config.php


- name: (WORDPRESS) Restart nginx
  service: name=nginx state=restarted

- name: (WORDPRESS) Create user deployeer
  user:
    name: deployeer
    create_home: no
    shell: /bin/false

- name: Generate SSH key
  shell: >
   su deployeer -c "ssh-keygen -t rsa -b 4096 -N \"\" -f ~/.ssh/id_rsa.pub && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"