- name: systemd reload
  systemd:
    daemon_reload: yes
    
- name: reload_prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200---
# handlers file for roles/prometheus
