---
# tasks file for grafana
- name: (GRAFANA) Install Grafana Web Server on RedHat Family
  yum:
    name=https://centos.pkgs.org/8-stream/centos-appstream-aarch64/grafana-7.5.15-2.el8.aarch64.rpm.html
    state=present

- name: (GRAFANA) Start service grafana-server, if not started
  ansible.builtin.service:
    name: grafana-server
    state: started

- name: (GRAFANA) Enable grafana
  shell: >
     /sbin/chkconfig --add grafana-server