---
# tasks file for grafana
- name: (GRAFANA) Install Grafana Web Server on RedHat Family
  yum:
    name=https://dl.grafana.com/enterprise/release/grafana-enterprise-9.0.6-1.x86_64.rpm
    state=present

- name: (GRAFANA) Start service grafana-server, if not started
  ansible.builtin.service:
    name: grafana-server
    state: started

- name: (GRAFANA) Enable grafana
  shell: >
     /sbin/chkconfig --add grafana-server