---
# tasks file for grafana
- name: (GRAFANA) Install Grafana Web Server on RedHat Family
  yum:
    name=http://mirror.centos.org/altarch/7/updates/aarch64/Packages/pcp-webapp-grafana-4.3.2-13.el7_9.noarch.rpm
    state=present

- name: (GRAFANA) Start service grafana-server, if not started
  ansible.builtin.service:
    name: grafana-server
    state: started

- name: (GRAFANA) Enable grafana
  shell: >
     /sbin/chkconfig --add grafana-server