---
# tasks file for grafana
- name: Install Grafana Web Server on RedHat Family
  yum:
    name=https://grafanarel.s3.amazonaws.com/builds/grafana-2.6.0-1.x86_64.rpm
    state=present

- name: Start service grafana-server, if not started
  ansible.builtin.service:
    name: grafana-server
    state: started

- name: Enable grafana
  shell: >
     /sbin/chkconfig --add grafana-server