#!/usr/bin/env ansible-playbook
---
  - name: Configure webserver nginx
    hosts: nodes
    become: yes
    become_user: root
    remote_user: centos
    vars:
      ansible_python_interpreter: /usr/bin/python
    tasks:
      - name: install EPEL repo
        become: yes
        yum: name=epel-release state=present

      - name: Install Nginx Web Server on RedHat Family
        yum:
            name=nginx
            state=latest

      - name: restart nginx
        service: name=nginx state=restarted



