---
- name: (PROMETHEUS) Create User prometheus
  user:
    name: prometheus
    create_home: no
    shell: /bin/false
 
- name: (PROMETHEUS) Create directories for prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - '/tmp/prometheus'
    - '/etc/prometheus'
    - '/var/lib/prometheus'
 
- name: (PROMETHEUS) Download And Unzipped Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prom_version }}/prometheus-{{ prom_version }}.linux-amd64.tar.gz
    dest: /tmp/prometheus
    creates: /tmp/prometheus/prometheus-{{ prom_version }}.linux-amd64
    remote_src: yes
 
- name: (PROMETHEUS) Copy Bin Files From Unzipped to Prometheus
  copy:
    src: /tmp/prometheus/prometheus-{{ prom_version }}.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'prometheus', 'promtool' ]
 
- name: (PROMETHEUS) Copy Conf Files From Unzipped to Prometheus
  copy:
    src: /tmp/prometheus/prometheus-{{ prom_version }}.linux-amd64/{{ item }}
    dest: /etc/prometheus/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'console_libraries', 'consoles', 'prometheus.yml' ]
 
- name: (PROMETHEUS) Create File for Prometheus Systemd
  template:
    src=templates/prometheus.service
    dest=/etc/systemd/system/
  notify:
    - systemd reload

- name: (PROMETHEUS) Apply Prometheus template
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml
 
- name: (PROMETHEUS) Copy alert_rules
  copy: src=files/alert_rules.yml dest=/etc/prometheus/

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /etc/prometheus/alert_rules.yml
    owner: prometheus
    group: prometheus
 

- name: (PROMETHEUS) Systemctl Prometheus Start
  systemd:
    name: prometheus
    state: started
    enabled: yes
