---
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present

    
- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest

- name: Copy nginx config file
  copy: src=files/nginx.conf dest=/etc/nginx/
          
- name: Restart nginx
  service: name=nginx state=restarted




