---
- name: (NGINX for APP) Install Nginx Web Server 
  yum:
    name=nginx
    state=latest

- name: (NGINX for APP) Copy nginx config file
  copy: src=files/nginx.conf dest=/etc/nginx/
          
- name: (NGINX for APP) Restart nginx
  service: name=nginx state=restarted