---
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present

    
- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest

- name: copy nginx config file
  copy: src=files/nginx.conf dest=/etc/nginx/


- name: set sebook
  shell: > 
    setsebool -P httpd_can_network_connect 1

- name: set sebook
  shell: > 
    setenforce 0

- name: Apply /etc/selinux/config
  template:
    src: templates/config.j2
    dest: /etc/selinux/config
          
- name: Restart nginx
  service: name=nginx state=restarted




