---
- hosts: all
  gather_facts: true
  become:
    true
  become_user:
    root
  remote_user:
    centos
  tasks:
   - name: install nano
     yum: name=nano state=latest

- hosts: 
    proxy
  become:
    true
  become_user:
    root
  remote_user:
    centos
  vars:
    domain_name: www.grachikn.ru
    letsencrypt_email: ngrachik2011@gmail.com
  roles:
    # 
    # - letsencrypt
     - nginx-proxy
    #  - letsnginx
     
     
- hosts: 
      app
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
     - nginx
