---
  - name: Check connetcions
    hosts: nodes
    tasks:     
      - name: Ping nodes
        ping:
    roles:
      # - mysql
      - wordpress
      - nginx

  # - name: Install MySQL
  #   hosts: db
  #   roles:
  #      - mysql

  # - name: Install wordpress
  #   hosts: app
  #   roles:
  #      - wordpress


  # - name: Deploy NGINX and Letsencrypt
  #   hosts: nginx
    
  #   roles:
  #      - nginx
  #      - letsencrypt




