---
- hosts: 
      proxy
  become:
    true
  become_user:
    root
  remote_user:
    centos
  vars:
    domain_name: www.grachikn.ru
    letsencrypt_email: ngrachik2011@gmail.com
  roles:
     - nginx-proxy
     - letsencrypt

# - hosts: nodes
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#    - nodeexport

