---
- hosts: all
  gather_facts: true
  tasks:
   - name: set sebook
     shell: 'setsebool -P httpd_can_network_connect 1'

- hosts: 
      proxy
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
     - nginx-proxy

- hosts: 
      app
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
     - nginx
