---
- hosts: 
      proxy
  become:
    true
  become_user:
    root
  remote_user:
    centos
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
  roles:
     - nginx

# - hosts: nodes
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#    - nodeexport

