---
- hosts: 
      nginx
      app
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
     - nginx

# - hosts: wordpress
#   become:
#     true
#   become_method:
#     sudo
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#    - wordpress

