---
- hosts: 
      proxy
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
     - role: julienpalard.nginx_letsencrypt
       vars:
         letsencrypt_certificates: [[grachikn.ru, www.grachikn.ru, grafana.grachikn.ru]]
         letsencrypt_email: ngrachik2011@gmail.com

# - hosts: nodes
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#    - nodeexport

