---
- hosts: all
  gather_facts: true
  become:
    true
  become_user:
    root
  remote_user:
    centos
  tasks:
  - name: Turn off setsebool 
    shell: > 
        setsebool -P httpd_can_network_connect 1
  - name: Turn off setenforce
    shell: > 
        setenforce 0
  - name: Copy SE config
    template:
      src: templates/conf.j2
      dest: /etc/selinux/config
  - name: Install epel-release
    yum:
      name=epel-release
      state=present


- hosts: 
      all
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
     - node-exporter
      

# - hosts: db_master
#   gather_facts: false
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#        - mysql-master


# - hosts: db_slave
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#        - mysql-slave
     
# - hosts: 
#       app
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#      - nginx
#      - wordpress

- hosts: 
    monitoring
  become:
   true
  become_user:
   root
  remote_user:
    centos
  roles:
   - prometheus
   - alertmanager
   - grafana

# - hosts: 
#     gitlab
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#     - gitlab-ce
#     - runner

- hosts: 
    proxy
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
    - nginx-proxy
    # - letsencrypt