---
- hosts: all
  gather_facts: true
  become:
    true
  become_user:
    root
  remote_user:
    centos

- hosts: 
      db_master
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
       - mysql-master
  
# - hosts: 
#       db-slave
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#        - mysql-slave

# - hosts: 
#       app
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#      - nginx

# - hosts: 
#     proxy
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#     - nginx-proxy
#     - letsencrypt


# - hosts: 
#       all
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   roles:
#      - node-exporter

# - hosts: all
#   gather_facts: true
#   become:
#     true
#   become_user:
#     root
#   remote_user:
#     centos
#   tasks:
#    - name: install nano
#      yum: name=nano state=latest

# - hosts: 
#     monitoring
#   become:
#    true
#   become_user:
#    root
#   remote_user:
#     centos
#   roles:
#    - prometheus
#    - alertmanager
#    - grafana