---
- hosts: all
  gather_facts: true
  become:
    true
  become_user:
    root
  remote_user:
    centos
  tasks:
   - name: set sebook
     shell: 'setsebool -P httpd_can_network_connect 1'

- hosts: 
      proxy
  become:
    true
  become_user:
    root
  remote_user:
    centos
  vars:
    service_host: "www.grachikn.ru"
    service_admin_email: "ngrachik2011@gmail.com"
    service_name: "service_name"
    service_root_directory: "/opt"
    letsencrypt_ssl_dir: "/etc/letsencrypt/live"
  roles:
    - nginx-proxy
    - letsencrypt

- hosts: 
      app
  become:
    true
  become_user:
    root
  remote_user:
    centos
  roles:
     - nginx
