---
  - name: Check connetcions
    hosts: nodes
    tasks: 
    
      - name: Ping nodes
        ping:

  # - name: Deploy NGINX and Letsencrypt
  #   hosts: nginx
    
  #   roles:
  #      - nginx
  #      - letsencrypt

  # - name: Install wordpress
  #   hosts: app
  #   roles:
  #      - wordpress

  - name: Install MySQL
    hosts: db
    roles:
       - mysql
