---
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present
 
- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - nginx systemd

- name: Apply Nginx template
  template:
    src: templates/nginx.conf.v2.j2
    dest: /etc/nginx/nginx.conf
           
- name: Restart nginx
  service: name=nginx state=restarted
  when: test_running_nginx.stdout != "" and test_nginx_config.rc == 0

- name: set sebook
  shell: 'setsebool -P httpd_can_network_connect 1'