---
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present
 
- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - nginx systemd

- name: Apply Nginx template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
           
- name: Nginx reload
  shell: service nginx restart

- name: set sebook
  shell: 'setsebool -P httpd_can_network_connect 1'