---
# - name: (NGINX for PROXY) Install EPEL Repo
#   yum:
#     name=epel-release
#     state=present
 
- name: (NGINX for PROXY) Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - nginx systemd

- name: (NGINX for PROXY) Apply Nginx template
  template:
    src: templates/nginx.conf.v2.j2
    dest: /etc/nginx/nginx.conf
           
- name: (NGINX for PROXY) Restart nginx
  service: name=nginx state=restarted