---

- name: Install nginx and certbot for letsencrypt
  package:
    state: present
    name:
      - nginx
      - certbot
      - ca-certificates
      - python-certbot-nginx

- name: Create SSL dhparam
  get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/ssl/certs/dhparam.pem
    mode: 0644

# This is usefull in case nginx already has an include to this file,
# to avoid nginx to fail parsing its configuration when certbot
# modifies it.
- name: Create letsencrypt snippets files
  file:
    path: '/etc/nginx/snippets/{{ snippet_prefix }}{{ item[0] }}.conf'
    state: file
    mode: 0644
  loop: '{{ letsencrypt_certificates }}'
  loop_control:
    label: "{{ item[0] }}"

- name: Create a new certificate
  shell: 'certbot certonly --cert-name {{ item[0] }} -n --agree-tos -d {{ item | join(",") }} -m {{ letsencrypt_email }} --nginx --rsa-key-size {{ rsa_key_size }}'
  loop: '{{ letsencrypt_certificates }}'
  loop_control:
    label: "{{ item[0] }}"
  register: certbot
  changed_when: '"Cert not yet due for renewal" not in certbot.stderr'

- name: Create letsencrypt snippets
  template:
    src: letsencrypt.conf.j2
    dest: '/etc/nginx/snippets/{{ snippet_prefix }}{{ item[0] }}.conf'
  loop: '{{ letsencrypt_certificates }}'
  loop_control:
    label: "{{ item[0] }}"
