- name: Show me var
  debug: msg="{{ hostvars['db01.grachikn.ru']['myvar2'] }}"


- name: Create a directory for MySQL
  ansible.builtin.file:
    path: /home/mysql
    state: directory

- name: Download file MySQL
  ansible.builtin.get_url:
    url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    dest: /home/mysql
   
- name: rpm MySQL
  command: rpm -ivh /home/mysql/mysql-community-release-el7-5.noarch.rpm
  ignore_errors: True


- name: Install updates
  yum: name=* state=latest

- name: Install MySQL
  yum:
    name=mysql-server
    state=latest
    
- name: Check version
  ansible.builtin.shell: > 
      mysql -uroot -e 'SELECT version();'
  register: version


- name: PRINT OUT THE OUTPUT VARIABLE
  debug:
       var: version.stdout_lines[1]

       
- name: Apply config
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf

- name: Restart service mysqld
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: mysqld


- name: Exec cmd Stop slave
  shell: >
     mysql -uroot -e "STOP SLAVE;"


- name: Exec CHANGE MASTER TO MASTER_HOST
  shell: >
     mysql -uroot -e "CHANGE MASTER TO MASTER_HOST='{{ hostvars['db01.grachikn.ru']['ansible_default_ipv4']['address'] }}', MASTER_USER='replica', MASTER_PASSWORD='strong_password', MASTER_LOG_FILE='{{ hostvars['db01.grachikn.ru']['my_var1'] }}', MASTER_LOG_POS='{{ hostvars['db01.grachikn.ru']['my_var2'] }}'';"


