---
# tasks file for mysql-master

- name: wget MySQL
  shell: wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm && rpm -ivh mysql-community-release-el7-5.noarch.rpm

- name: Install updates
  yum: name=* state=latest
  when: ansible_os_family == "RedHat

- name: Install MySQL
  yum:
    name=mysql-server
    state=latest

- name: Check version
  command: mysql -uroot -e 'SELECT version();'
  register: mysqlversion

- name: start mariadb
  service: name=mariadb state=started enabled=yes

- name: Apply config
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf

- name: Restart service mysqld
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: mysqld

- name: Create user replica
  command: mysql -uroot -e CREATE USER 'replica'@'{{ hostvars['db02.grachikn.ru']['ansible_default_ipv4']['address'] }}' IDENTIFIED BY 'replica';
