---
# tasks file for mysql-master

- name: Create a directory for MySQL
  ansible.builtin.file:
    path: /home/mysql
    state: directory

- name: Download file MySQL
  ansible.builtin.get_url:
    url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    dest: /home/mysql
   
- name: rpm MySQL
  command: rpm -ivh /home/mysql/mysql-community-release-el7-5.noarch.rpm
  ignore_errors: True


- name: Install updates
  yum: name=* state=latest

- name: Install MySQL
  yum:
    name=mysql-server
    state=latest
  
  
- name: start mysqld
  service: name=mysqld state=started enabled=yes

- name: Check version
  ansible.builtin.shell: > 
      mysql -uroot -e 'SELECT version();'
  register: version

- name: PRINT OUT THE OUTPUT VARIABLE
  debug:
       var: version.stdout_lines[1]
       
- name: Apply config
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
  when: ansible_host == "{{ hostvars['db01.grachikn.ru']['ansible_default_ipv4']['address'] }}"

- name: Restart service mysqld
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: mysqld
  when: ansible_facts['ansible_hostname'] == "db01"

- name: Create user replica
  shell: >
     mysql -uroot -e "CREATE USER 'replica'@'{{ db2 }}' IDENTIFIED BY 'replica';"
  when: ansible_facts['ansible_hostname'] == "db01"
  

- name: Grant previllegies
  shell: >
     mysql -uroot -e "GRANT REPLICATION SLAVE ON *.* TO 'replica'@'{{ db2 }}';"
  when: ansible_facts['ansible_hostname'] == "db01"
  

- name: Get var1
  shell: > 
      mysql -uroot -e "SHOW MASTER STATUS;" | grep mysql-bin | awk '{print $1}'
  register: var1
  when: ansible_facts['ansible_hostname'] == "db01"

- name: Set var1
  set_fact:
    my_var1: "{{ var1.stdout_lines[0] }}"
  when: ansible_facts['ansible_hostname'] == "db01"

- name: PRINT OUT my_var1
  debug:
       var: my_var1
  when: ansible_facts['ansible_hostname'] == "db01"

- name: Get var2
  shell: > 
      mysql -uroot -e "SHOW MASTER STATUS;" | grep mysql-bin | awk '{print $2}'
  register: var2
  when: ansible_facts['ansible_hostname'] == "db01"

- name: Set var2
  set_fact:
    my_var2: "{{ var2.stdout_lines[0] }}"
  when: ansible_facts['ansible_hostname'] == "db01"

- name: PRINT OUT my_var2
  debug:
       var: my_var2
  when: ansible_facts['ansible_hostname'] == "db01"
             

- name: Create database WORDPRESS
  shell: >
     mysql -uroot -e "CREATE DATABASE wordpress;"
  when: ansible_facts['ansible_hostname'] == "db01"

- name: Create user worpdress
  shell: >
     mysql -uroot -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'replica';"     
  when: ansible_facts['ansible_hostname'] == "db01"

- name: Grant previllegies
  shell: >
     mysql -uroot -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'worpress'@'localhost';"
  when: ansible_facts['ansible_hostname'] == "db01"
 