---
# tasks file for mysql-master
- name: Install wget
  yum:
    name=wget
    state=latest 

- name: Create a directory for MySQL
  ansible.builtin.file:
    path: /home/mysql
    state: directory

- name: Download file MySQL
  ansible.builtin.get_url:
    url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    dest: /home/mysql
   
- name: rpm MySQL
  command: rpm -ivh /home/mysql/mysql-community-release-el7-5.noarch.rpm
  ignore_errors: True

- name: Install updates
  yum: name=* state=latest

- name: Install MySQL
  yum:
    name=mysql-server
    state=latest

- name: start mysqld
  service: name=mysqld state=started enabled=yes

- name: Check version
  command: mysql -uroot -e 'SELECT version();'

- name: Apply config
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf

- name: Restart service mysqld
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: mysqld

- name: Create user replica
  shell: mysql -uroot -e CREATE USER 'replica'@'{{ db2 }}' IDENTIFIED BY 'replica';
